version: '2'
services:
  fluentd:
    build: ./fluentd
    volumes:
      - ./fluentd/etc:/fluentd/etc
    ports:
      - "8888:8888"
  memcached:
    image: memcached:1.4.31-alpine
    ports:
      - "11211:11211"
  mysql:
    image: mysql:5.6
    volumes:
      - ./mysql/docker-entrypoint.sh:/usr/local/bin/docker-entrypoint.sh
      - ./mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
      - "11222:11222"
    environment:
      MYSQL_ROOT_PASSWORD: root
